#SPDX-License-Identifier: MIT-0
---
- include_tasks: "install-nginx-{{ansible_distribution|lower}}.yml"
- include_tasks: "start-nginx-{{ansible_distribution|lower}}.yml"
- include_tasks: common-nginx-tasks.yml
- include_tasks: "configure-nginx-{{ansible_distribution|lower}}.yml"
