- name: Install Extra Packages for Enterprise Linux (epel-release) in Rocky ansible node
  yum: name=epel-release state=latest 

- name: Install nginx web server in Rocky ansible node
  yum: name=nginx state=latest 
